version: '3.8'
services: 
  app:
    build: .
    command: app.py
    environment:
      - REDIRECT_URL=127.0.0.1:5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
        - db
    
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=door_lock_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ds*s***
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    ports:
      - 27017:27017